### ISSUE TITLE
Add working links

### ISSUE THREAD

**Issue by mithintv** [mithintv/film-portfolio#1]
### Tasks
- [x] Create pages for each link in nav bar
- [x] Fill About page with bio
- [x] Fill About page with photo
- [x] Fill Contact page with contact form
