### ISSUE TITLE
Add Email JS

### ISSUE THREAD

**Issue by mithintv** [mithintv/film-portfolio#12]
### Tasks

- [x] Add useReducer to contact form
- [x] Add form validation
- [x] Add form reset
- [x] Add emailjs to contact form
- [x] Ensure data is received in form submission
