### ISSUE TITLE
Add Dark Theme

### ISSUE THREAD

**Issue by mithintv** [mithintv/film-portfolio#14]
### Tasks

- [ ] Add theming switch
- [ ] Add dark theme options
- [ ] Adjust switch to take new theme
