### ISSUE TITLE
Animation on Load

### ISSUE THREAD

**Issue by mithintv** [mithintv/film-portfolio#19]
### Tasks

- [x] Image to call function after load
- [x] Function to be called by ProjectList
- [x] ProjectList keeps frequency counter of function calls based on # of projects
- [x] ProjectList sends state to each project upon load completion
- [x] Project to accept load state to fade in
- [x] Add Fade in for modal
- [x] Add Fade out for modal
- [ ] Fix bump on detail zooms (i.e. unladylike)
- [ ] Adjust social on mobile index page
