### ISSUE TITLE
Schema for projects

### ISSUE THREAD

**Issue by mithintv** [mithintv/film-portfolio#2]
### Tasks
- [x] Adjust database data
- [x] Provision database and schema for projects
- [x] Insert all project assets into database for access
