### ISSUE TITLE
Add Social Icons

### ISSUE THREAD

**Issue by mithintv** [mithintv/film-portfolio#5]
### Tasks
- [x] Add desktop/tablet social icons
- [x] Style desktop/tablet social icons
- [x] Style mobile social icons
