### ISSUE TITLE
Add DB

### ISSUE THREAD

**Issue by mithintv** [mithintv/film-portfolio#8]
### Tasks
- [x] Connect to DB
- [x] Add data to narrative page
- [x] Add data to music video page
- [x] Add data to commercial page
- [x] Add data to non fiction page
