### ISSUE TITLE
Style

### ISSUE THREAD

**Issue by mithintv** [mithintv/film-portfolio#9]
### Tasks

- [x] Style project grid
- [x] Hover animation for grid
- [x] Fade animation for grid
- [x] Slide animation for grid
- [x] Fix media queries
- [x] Style mobile nav bar
- [x] Style color scheme
- [x] Make contact form more efficient
- [x] Add submit button
